from tile import *
class FeatureData:
    features = {
        'door': {
            'tile': Door,
            'state': 'closed',
            'color': 'black',
            'random': False,
            'lures': [],
        },
        'stair': {
            'tile': Stair,
            'state': 'up',
            'color': 'black',
            'random': False,
            'lures': [],
        },
        'stair': {
            'tile': Stair,
            'state': 'down',
            'color': 'black',
            'random': False,
            'lures': [],
        },
        'floor': {
            'tile': Floor,
            'color': 'black',
            'random': False,
            'lures': [],
        },
        'wall': {
            'tile': Wall,
            'color': 'black',
            'random': False,
            'lures': [],
        },
        'spring': {
            'tile': Water,
            'depth': 'shallow',
            'state': 'fresh',
            'color': 'blue',
            'random': True,
            'rarity': 3,
            'lures': ['TR_SWIM'],
        },
        'hot_spring': {
            'tile': Water,
            'depth': 'shallow',
            'state': 'sulfurous',
            'color': 'cyan',
            'random': True,
            'rarity': 3,
            'lures': [],
        },
        'pool': {
            'tile': Water,
            'depth': 'shallow',
            'state': 'fresh',
            'color': 'blue',
            'random': True,
            'rarity': 2,
            'lures': ['TR_SWIM'],
        },
        'stag_pool': {
            'tile': Water,
            'depth': 'shallow',
            'state': 'stagnant',
            'color': 'blue',
            'random': True,
            'rarity': 2,
            'lures': ['TR_SWIM'],
        },
        'rock': {
            'tile': Rock,
            'color': 'gray',
            'random': True,
            'rarity': 1,
            'lures': [],
        },

    }
